# docker-compose.yml

services:
  db:
    image: postgres:15
    container_name: todo-db
    restart: always
    environment:
      POSTGRES_USER: silky
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: tododb
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - todo-net

  backend:
    build: ./backend
    container_name: todo-backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_USER=silky
      - DB_PASS=secret123
      - DB_NAME=tododb
    networks:
      - todo-net

  frontend:
    build: ./frontend
    container_name: todo-frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    networks:
      - todo-net

volumes:
  db-data:

networks:
  todo-net:
